source 'https://rubygems.org'
gem 'github-pages'
gem 'jekyll-paginate'
gem 'jekyll-paginate-v2'
gem 'jekyll-babel'
gem 'jekyll-toc', '~> 0.17.1'
gem 'jekyll-roman', '= 0.0.1'
gem 'nokogiri', '~> 1.13.3'
gem 'rake', '>= 13.0.1'
gem 'rspec', '>= 3.0'
gem "webrick", "~> 1.7"
